config/routes.rb
Swhealth::Application.routes.draw do
  resources :categories
  resources :providers

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :provider
  attr_accessible :name
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :categories
  attr_accessible :address1, :fax, :firstName, :glat, :glong, :name, :orgName, :orgSubType, :orgType, :phone, :postCode, :providerName, :providerNumber, :state, :suburb, :title, :category_id

def self.search(search)
  search_condition = "%" + search + "%"
  find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    if(params[:category_id])
      puts params[:category_id]
      redirect_to category_path(params[:category_id]) and return
    end
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @categories = Category.all
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @providers }
    end
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
    @provider = Provider.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @provider }
    end
  end

  # GET /providers/new
  # GET /providers/new.json
  def new
    @provider = Provider.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @provider }
    end
  end

  # GET /providers/1/edit
  def edit
    @provider = Provider.find(params[:id])
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(params[:provider])

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render json: @provider, status: :created, location: @provider }
      else
        format.html { render action: "new" }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /providers/1
  # PUT /providers/1.json
  def update
    @provider = Provider.find(params[:id])

    respond_to do |format|
      if @provider.update_attributes(params[:provider])
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider = Provider.find(params[:id])
    @provider.destroy

    respond_to do |format|
      format.html { redirect_to providers_url }
      format.json { head :no_content }
    end
  end

  def search
    @grants = Grant.search params[:search]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Categories

%table{:class => ['table', 'table-bordered']}
  %tr
    %th Choose your Category


  - @categories.each do |category|
    %tr
      %td= link_to category.name, category
-#      %td= link_to 'Show', category
-#      %td= link_to 'Edit', edit_category_path(category)
-#      %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %h2 Name:
  = @category.name
  
%p
  %b Providers
  %table{:class => ['table', 'table-striped']}
    %tr
      %th Name
      %th Address
      %th Doctor Name
    -@category.provider.each do |provider|
      %tr
        %td=link_to provider.name, provider
        %td=provider.address1
        %td=provider.firstName
%br
-#= link_to 'Edit', edit_category_path(@category)
-#\|
-#= link_to 'Back', categories_path

app/views/home/index.html.haml
%div.splash
  =image_tag("logo.png")
  = link_to image_tag("page 1.png"), categories_path
  %hr
  %br
  %h3.center Find your next health provider
  %form{:method => "get",:action=>"categories"}
    %div.navigation
      %div.segment.first
        %label Select a category
        %select{:name => "category_id"}
          - @categories.each do |category|
            %option{ :value => category.id} #{category.name}
      %div.segment.second
        %label Select your health insurance
        %select
          %option Bupa
          %option Health Partners
          %option Medibank Private
          %option Police Health
      %div.segment.third
        %label Enter your Location
        %input 
      %div.clear  
    %div.centerbutton
      %button.btn.btn-warning.btn-large{:href => category_path(1)}>Search Now
    %div.clear  
    %br
    %br
    %hr
      

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-#= link_to "Swhealth", root_path, :class => 'brand'
= link_to image_tag("logo.png", :class => "logo"), root_path
%ul.nav
  %li 
    = link_to 'Choose Category', categories_path
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Swhealth"
      %meta{:content => content_for?(:description) ? yield(:description) : "Swhealth", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/providers/_form.html.haml
= simple_form_for(@provider) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title  
    = f.input :name
    = f.input :phone  
    = f.input :fax
    = f.input :firstName
    = f.input :glat
    = f.input :glong
    = f.input :orgName
    = f.input :orgSubType
    = f.input :orgType
    = f.input :postCode
    = f.input :providerName
    = f.input :providerNumber
    = f.input :state
    = f.input :suburb
    = f.input :category_id
	

  .form-actions
    = f.button :submit

app/views/providers/edit.html.haml
%h1 Editing provider

= render 'form'

= link_to 'Show', @provider
\|
= link_to 'Back', providers_path

app/views/providers/index.html.haml
%h1 Listing providers

%table
  %tr
    %th
    %th
    %th

  - @providers.each do |provider|
    %tr
      %td= provider.name
      %td= link_to 'Show', provider
      %td= link_to 'Edit', edit_provider_path(provider)
      %td= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Provider', new_provider_path

app/views/providers/new.html.haml
%h1 New provider

= render 'form'

= link_to 'Back', providers_path

app/views/providers/show.html.haml
%p#notice= notice


%div.image
  =image_tag ("http://placesheen.com/250/350?unique="+SecureRandom.urlsafe_base64)

%div.description
  %p
    %b Name:
    = @provider.name
  %p
    %b Practitioner:
    = @provider.title 
    = @provider.firstName    
  %p 
    %b Phone:
    = @provider.phone
  %p 
    %b Fax:
    = @provider.fax    
  %p
    %b Address:
    = @provider.address1
  %p 
    %b Suburb:
    = @provider.suburb  
  %p 
    %b State:
    = @provider.state  
  %p 
    %b Postcode:
    = @provider.postCode             
  %hr
  %p
    %b Current Rating
    =image_tag ("4stars.jpg"),{:class => "stars"}



-#= link_to 'Edit', edit_provider_path(@provider)
-#\|
-#= link_to 'Back', providers_path

%div.book
  %button.btn.btn-success.btn-large Book Now

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}